apiVersion: v1
kind: Service
metadata:
  name: greeter
  labels: 
    app: greeting
spec:
  selector:
    app: greeter
  ports:
  - name: http
    port: 80
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
        version: v1
    spec:
      containers:
      - name: greeting
        image: "chuzy/greeterservice:1.0"
        ports:
        - containerPort: 80 
        
        